# This is a basic workflow to help you get started with Actions

name: Flutter Build for Android

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install Flutter
      run: ./install_flutter.sh
    - name: Build app
      run: |
        cd $GITHUB_WORKSPACE
        ./fix_environment.sh
        cd $GITHUB_WORKSPACE/apps/sysui
        source tools/environment.sh
        cd $GITHUB_WORKSPACE/apps/sysui/armadillo
        flutter build appbundle --debug
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: Pangolin APKs
        # Directory containing files to upload
        path: $GITHUB_WORKSPACE/apps/sysui/armadillo/build/app/outputs/
